### ISSUE TITLE
withCancellingContinutation has a typo

### ISSUE THREAD

**Issue by gparker42** [ChimeHQ/ConcurrencyPlus#2]
`withCancellingContinutation` has a typo
`withCancellingContinuation` is correct

**Comment by mattmassicotte** [comment]
What’s amazing here is I spelled “cancelling” correct

**Comment by mattmassicotte** [comment]
Fixed with https://github.com/ChimeHQ/ConcurrencyPlus/commit/180b20b7fcea75ca52a3f15e84ab52a17d46b3eb
