### ISSUE TITLE
Puzzled about `testOrdered`

### ISSUE THREAD

**Issue by finestructure** [ChimeHQ/ConcurrencyPlus#3]
Hey Matt, I was looking at the tests to try and understand how task ordering would manifest itself. When I saw `testOrdered`:

```swift
    func testOrdered() async {
        var array = [Int]()

        for i in 0..<1000 {
            let task: Task<Int, Never> = Task.ordered { return i }

            array.append(await task.value)
        }

        let sorted = array.sorted()

        XCTAssertEqual(array, sorted)
    }
```

I wondered: Doesn't the `await` inside the loop essentially force the result ordering regardless of the type of scheduling you're doing?

I tried to rewrite the test in order to understand and both of these variants pass:

```swift
    func testUnordered() async {
        var tasks = [Task<Int, Never>]()
        for i in 0..<1000 {
            let task: Task<Int, Never> = Task { return i }
            tasks.append(task)
        }

        var array = [Int]()
        for t in tasks {
            array.append(await t.value)
        }

        let sorted = array.sorted()

        XCTAssertEqual(array, sorted)
    }

    func testOrdered() async {
        var tasks = [Task<Int, Never>]()
        for i in 0..<1000 {
            let task: Task<Int, Never> = Task.ordered { return i }
            tasks.append(task)
        }

        var array = [Int]()
        for t in tasks {
            array.append(await t.value)
        }

        let sorted = array.sorted()

        XCTAssertEqual(array, sorted)
    }
```

In fact, it's unclear to me how you'd _not_ get an ordered result if you await the results in a loop that's ordered by task submission.

Is there even an async/await API (outside TaskGroup) that allows you to await tasks that are running concurrently and that'd give you a random order?

I guess what I'm trying to say is: Where would you use `Task.ordered { }` in a way that'd give different results than just plain `Task { }`?

I'm merely asking to better understand how this aspect of async/await works, not trying to question the utility of the package! :)

**Comment by mattmassicotte** [comment]
Hi Sven! I really appreciate you taking the time to write up such a detailed question. You are totally correct that this is a kind of a strange test. It was really more about verifying that the call was doing **something** correct, and less about specifically exercising the cases that are problematic.

Without `Task.ordered` the ordering of task execution starts is entirely at the discretion of the system. They could *often* be run in order, but they are not required to. And I can assure you that they definitely do not in the general case. You must use *await* to enforce an ordering, and that's exactly what `TaskQueue` does. This test just happens to not expose the problematic situations well.

The underlying problem I faced in my app that motivated this work was totally disconnected components that do work that have very strict ordering requirements. In theory, I could have enforced this ordering with `await`, as you suggest. But making it possible to get the needed `Task` instances to the right places was just totally infeasible. In fact, I didn't even **realize** this was a problem until my app started breaking in strange ways. It took me days of debugging before I figured out that without explicitly ordering tasks via `await`, the ordering is undefined.

**Comment by finestructure** [comment]
I think I've come up with a way to describe the problem in simple terms: How do you test that something's running without strict ordering requirements (just `Task {}`) to prove the ordered variant is working (`Task.ordered {}`) when your only mechanism to extract the results is in the order you're trying to test for.

I've updated the test to this and now it fails if you replace `Task.ordered {}` with `Task {}`:

```swift
    func testOrdered() async {
        var tasks = [Task<TimeInterval, Never>]()
        for _ in 0..<1_000 {
            let task = Task.ordered { Date().timeIntervalSince1970 }
            tasks.append(task)
        }

        var array = [TimeInterval]()
        for t in tasks {
            array.append(await t.value)
        }

        XCTAssertEqual(array, array.sorted())
    }
```

I think this also illustrates the kinds of use cases you might have even if your results access is ordered. For instance I could imagine you have some work queue you need to drain in order, or need db records you create have ordered ids or something like that. The `Date` simulates that external dependency and bakes in the time of access.

I'll open a PR in case you fancy merging it. Thanks a lot for taking the time to reply! :)

**Comment by mattmassicotte** [comment]
Oh that's a brilliant way to do it! Thank you so much for putting the time in here. Definitely going to merge.
